### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by ivanadob** [acdh-oeaw/nomansland-website#2]
In card.astro the href in 
```
<h3 class="text-xl font-medium text-[#444]">
				<a class="hover:underline" href={link.href}>
```
leads to general oeaw and not specific nomad project site (https://www.oeaw.ac.at/about - should be probably - https://www.oeaw.ac.at/iran/nomansland/about) as in the href to img above.

**Comment by stefanprobst** [comment]
thanks for reporting! should be fixed now!
